replicaCount: 1

image:
  repository: ghcr.io/YOUR_GH_USERNAME/sample-app
  tag: "latest"
  pullPolicy: IfNotPresent
  # If you mark GHCR image as private, create a secret and set the name here
  pullSecrets: []  # e.g. ["ghcr-pull-secret"]

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your.domain
      paths:
        - path: /
          pathType: Prefix
  tls: []
